# Generated by Django 5.2.6 on 2026-05-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appbackend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("products", models.CharField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cerated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
