# Generated by Django 5.2.14 on 2026-05-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appbackend", "0002_sales"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sales",
            old_name="cerated_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="sales",
            name="customer_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sales",
            name="customer_phone",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sales",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="sales",
            name="products",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="Sale_Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_at_sale", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appbackend.product_inventory",
                    ),
                ),
                (
                    "sales",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="appbackend.sales",
                    ),
                ),
            ],
        ),
    ]
