# Generated by Django 5.2.14 on 2026-05-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appbackend", "0003_rename_cerated_at_sales_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
