# Generated by Django 5.2.14 on 2026-06-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appbackend", "0004_alter_sales_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_inventory",
            name="barcode",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sales",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
