# Generated by Django 5.2.6 on 2026-07-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appbackend", "0006_product_inventory_user_sales_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("percentage", "Percentage"), ("flat", "Flat")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sales",
            name="discount_value",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
